# Generated by Django 4.1.3 on 2022-11-23 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_comments_bids'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='bids',
            new_name='Bid',
        ),
        migrations.RenameModel(
            old_name='comments',
            new_name='Comment',
        ),
        migrations.RenameModel(
            old_name='listings',
            new_name='Listing',
        ),
    ]
