# Generated by Django 4.1.3 on 2022-11-23 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_rename_bids_bid_rename_comments_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='item',
            field=models.CharField(default='No item name provided', max_length=52),
        ),
    ]
