# Generated by Django 4.1.3 on 2022-11-23 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_listing_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='item',
        ),
        migrations.AddField(
            model_name='listing',
            name='item_description',
            field=models.CharField(default='No description provided.', max_length=280),
        ),
        migrations.AddField(
            model_name='listing',
            name='starting_bid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
