# Generated by Django 4.1.3 on 2022-11-23 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_remove_listing_item_listing_item_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='category',
            field=models.CharField(default='No categories provided.', max_length=280),
        ),
    ]
